name: First Trial Build and Package Backend app 

on:
  push:
    branches: 
      - "main"
    # paths:
    #   - "spring-boot-data-jpa-mysql-master/**"
    #   - ".github/workflows/maven-workflow.yml"
    #   - "!README.md"
    #   - "!spring-boot-data-jpa-mysql-master/README.md"

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd spring-boot-data-jpa-mysql-master
          mvn clean install -DskipTests

      - name: Archive JAR file
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: spring-boot-data-jpa-mysql-master/target/*.jar

  docker-build:
    runs-on: ubuntu-latest
    needs: maven-build
    services:
      mysql:
        image: mysql:8.2.0
        env:
          MYSQL_ROOT_PASSWORD: 123456
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download JAR file
        uses: actions/download-artifact@v4
        with:
          name: app
          path: spring-boot-data-jpa-mysql-master/target

      - name: Build Docker image
        run: |
          cd spring-boot-data-jpa-mysql-master
          docker build -f Dockerfile -t spacehz/backend-app:latest .

      - name: Log in to Docker Hub
        run: docker login -u spacehz -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the image to Docker Hub
        run: docker push spacehz/backend-app:latest
